config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'articles#index'

  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
  get 'users', to: 'users#index'
  delete 'users/:id', to: 'users#destroy', as: 'user_delete'

  get 'profile/:id/edit', to: 'users#edit', as: 'edit_user'
  put 'profile/:id', to: 'users#update', as: 'user'

  get 'home', to: 'home#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles do
    resources :comments
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images

  validates :title, presence: true,
            length: {minimum: 2, maximum: 150}
  validates :text, presence: true,
            length: {minimum: 2, maximum: 256 }
  validate :images_validate

  def images_validate
    # puts("IMAGES: #{images.attached?}")
    if images.attached?
      images.each do |image|
        # puts("IMAGE: #{image.content_type}")
        puts("IMAGE: #{image.filename}")
        if !image.content_type.start_with?('image')
          errors.add(:images, "The file #{image.filename} must be image file")
          # image.purge
        end
      end
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  skip_before_action :logged_in_user, only: [:index, :show]
  before_action :article_set, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found
  before_action -> { authorize @article || Article }

  def index
    @articles = Article.all
  end

  def show
    @comments = @article.comments.order('created_at DESC')
    @images = @article.images
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    @article.images = params[:article][:images]

    if @article.save
      flash[:success] = I18n.t 'article_crated'
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @article.assign_attributes article_params
    @article.images = params[:article][:images]
    if @article.save
      flash[:success] = I18n.t 'article_updated'
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = I18n.t 'article_deleted'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

  private

  def article_set
    @article = Article.find(params[:id])
  end

  private

  def handle_record_not_found
    flash[:danger] = I18n.t 'article_not_found'
    redirect_to articles_path
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="row mt-5">
  <div class="col-12 col-sm-10 col-lg-8 mx-auto">
    <div class="bg-white shadow p-5 mb-5">
      <h1 class="text-center"> <%= title %> </h1>
      <hr>

      <%= form_for(@article, local: true) do |f| %>
        <div class="form-group">
          <%= f.label 'Title:' %>
          <%= f.text_field :title, :autofocus => true, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @article.errors.messages[:title].first %>
          </small>
        </div>

        <div class="form-group">
          <%= f.label 'Content:' %>
          <%= f.text_area :text, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @article.errors.messages[:text].first %>
          </small>
        </div>

        <div class="form-group">
          <%= f.label 'Images' %>
          <%= f.file_field :images, multiple: true %>
          <small class="text-danger"> <%= @article.errors[:images].first %> </small>
        </div>


        <div class="row">
          <div class="col">
            <%= f.submit btnTxt, class: 'btn btn-primary btn-block btn-large' %>
          </div>

          <div class="col">
            <%= link_to 'Back', articles_path, class: 'btn btn-secondary btn-block' %>
          </div>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'articles/form', {title: 'Edit Article', btnTxt: 'Save'} %>

app/views/articles/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-sm-10 col-lg-10 mx-auto">
      <div class="bg-white shadow p-5 mb-5">
        <h1 class="text-center">Articles List</h1>

        <table class="table">
          <thead>
          <th>Title</th>
          <th>Content</th>
          <th>Created by</th>
          <th>Options</th>
          </thead>
          <tbody>
          <% @articles.each do |article| %>
            <tr>
              <td> <%= article.title %> </td>
              <td> <%= article.text %> </td>
              <td> <%= article.user.name %> </td>
              <td>
                <%= link_to 'Show', article_path(article) %>
                <% if logged_in? %>
                  <% if current_user.id == article.user.id %>
                    <%= link_to 'Edit', edit_article_path(article) %>
                    <%= link_to 'Delete', article_path(article),
                                method: :delete,
                                data: { confirm: 'Are you destroy this article?' }  %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'articles/form', {title: 'Create Article', btnTxt: 'Create'} %>

app/views/articles/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-sm-10 col-lg-8 mx-auto mb-5">
      <div class="bg-white shadow py-3 px-5">
        <h1 class="text-center"> <%= @article.title %></h1><hr>
        <p> <%= @article.text %> </p>
        <% @images.each do |image| %>
          <% if image.variable? %>
            <%= link_to image_tag(image.variant(resize: "200x200"), class: 'img-thumbnail shadow m-2'), image %>
          <% else %>
            <%= link_to (image.filename), image %>
          <% end %>
        <% end %>
      </div>

      <div class="bg-white shadow py-3 px-5 mt-3">
        <h1>Comments:</h1>
        <hr>
        <div id="comment_pane">
          <%#= render @comments %>
          <% @comments.each do |comment| %>
            <%= render 'comments/comment', comment: comment %>
          <% end %>
        </div>
      </div>

      <div class="bg-white shadow pt-3 pb-4 px-5 mt-3">
        <% if logged_in? %>
          <h1>Comment this article:</h1>
          <hr>
          <%= render 'comments/form' %>
        <% else %>
          <p>If you want comment this article please login ... <%= link_to 'click here for redirect', login_path %> </p>
        <% end %>
      </div>

    </div>
  </div>

</div>