config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'articles#index'

  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
  get 'users', to: 'users#index'
  delete 'users/:id', to: 'users#destroy', as: 'user_delete'

  get 'profile/:id/edit', to: 'users#edit', as: 'edit_user'
  put 'profile/:id', to: 'users#update', as: 'user'

  get 'home', to: 'home#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles do
    resources :comments
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  before_save   :downcase_email
  before_create :create_activation_digest

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :role
  has_one_attached :avatar

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_secure_password

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validate :correct_avatar_mime_type

  def correct_avatar_mime_type
    if avatar.attached? && !avatar.content_type.start_with?('image')
      errors.add(:avatar, "The file #{avatar.filename} must be a image")
    end
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def admin?
    role.code == 'ADMIN'
  end

  def normal_user?
    role.code == 'USER'
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :logged_in_user, only: [:new, :create]
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :set_roles, only: [:new, :create, :edit, :update]
  before_action -> { authorize @user || User }
  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if logged_in? && current_user.admin?
      @user.role = Role.find(params[:user][:role])
    else
      @user.role = Role.find_by(code: "USER")
    end
    if @user.save
     flash[:success] = I18n.t 'login_success'
     redirect_to users_path
    else
     render 'new'
    end
  end

  def edit
  end

  def update
    @user.assign_attributes user_params
    if logged_in? && current_user.admin?
      @user.role = Role.find(params[:user][:role])
    else
      @user.role = Role.find_by(code: "USER")
    end
    if @user.save
      flash[:success] = I18n.t 'user_update'
      if current_user.role.code == 'ADMIN'
        redirect_to users_path
      else
        redirect_to articles_path
      end

    else
      puts(@user.errors.inspect)
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = I18n.t 'user_delete'
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end

  private
  def handle_record_not_found
    flash[:danger] = I18n.t 'user_not_found'
    redirect_to home_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def set_roles
    @roles = Role.all
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row mt-5">
  <div class="col-12 col-sm-10 col-lg-8 mx-auto">
    <div class="bg-white shadow p-5 mb-5">
      <h1 class="text-center">Change your personal data</h1>

      <div class="row justify-content-center">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar.variant(resize: "200x200"), class: 'rounded-circle' %>
        <% else %>
          <%= image_tag "no-user.png", alt: "NO USER", size: "200", class: 'rounded-circle' %>
        <% end %>
      </div>

      <hr>
      <%= form_for @user, url: user_path, method: 'put' do |f| %>
        <div class="form-group">
          <%= f.label 'Name' %>
          <%= f.text_field :name, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @user.errors.messages[:name].first %>
          </small>
        </div>
        <div class="form-group">
          <%= f.label 'Email:' %>
          <%= f.email_field :email, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @user.errors.messages[:email].first %>
          </small>
        </div>

        <% if logged_in? && current_user.admin? %>
          <div class="form-group">
            <%= f.label 'Role:' %>
            <% @roles.each do |role| %>
              <div class="form-check">
                <%= f.radio_button :role, role.id, class: 'form-check-input',
                                   checked: !@user.role.nil? ? @user.role.id == role.id : false %>
                <%= f.label :role, role.name, class: 'form-check-label' %>
              </div>
            <% end %>
         </div>
        <% end %>

        <% if logged_in? && (current_user.admin? || current_user == @user) %>
          <div class="form-group">
            <%= f.label 'Avatar:' %>
            <%= f.file_field :avatar %>
            <small class="text-danger"> <%= @user.errors[:avatar].first %> </small>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label 'Password:' %>
          <%= f.password_field :password, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @user.errors.messages[:password].first %>
          </small>
        </div>
        <div class="form-group">
          <%= f.label 'Password confirmation' %>
          <%= f.password_field :password_confirmation, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @user.errors.messages[:password_confirmation].first %>
          </small>
        </div>
        <div class="row">
          <div class="col">
            <%= f.submit 'Save changes', class: 'btn btn-primary btn-block' %>
          </div>
          <div class="col">
            <%= link_to 'Cancel', users_path, class: 'btn btn-secondary btn-block' %>
          </div>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-sm-10 col-lg-10 mx-auto">
      <div class="bg-white shadow p-5 mb-5">
        <h1 class="text-center">Users List</h1>

        <table class="table">
          <thead>
          <th>Avatar</th>
          <th>Name</th>
          <th>Email</th>
          <th>Role</th>
          <th>Options</th>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <% if user.avatar.attached? %>
                  <%= image_tag user.avatar.variant(resize: "40x40"), class: 'rounded-circle' %>
                <% else %>
                  <%= image_tag "no-user.png", alt: "NO USER", size: "40", class: 'rounded-circle' %>
                <% end %>
              </td>
              <td> <%= user.name %> </td>
              <td> <%= user.email %> </td>
              <% if user.role %>
                <td> <%= user.role.name %> </td>
              <% else %>
                <td>No assigned role</td>
              <% end %>

              <td>
                <%= link_to 'Edit', edit_user_path(user) if policy(user).edit? %>
                <%= link_to 'Delete', user_delete_path(user),
                            method: :delete,
                            data: {confirm: 'Are you destroy this user?'} %>

              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row mt-5">
  <div class="col-12 col-sm-10 col-lg-8 mx-auto">
    <div class="bg-white shadow p-5 mb-5">
      <h1 class="text-center">Register</h1>
      <hr>
      <%= form_for @user, url: register_path, method: 'post' do |f| %>
        <div class="form-group">
          <%= f.label 'Name' %>
          <%= f.text_field :name, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @user.errors.messages[:name].first%>
          </small>
        </div>
        <div class="form-group">
          <%= f.label 'Email:' %>
          <%= f.email_field :email, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @user.errors.messages[:email].first%>
          </small>
        </div>

        <% if logged_in? && current_user.admin?%>
          <div class="form-group">
            <%= f.label 'Role:' %>
            <% @roles.each do |role| %>
              <div class="form-check">
                <%= f.radio_button :role, role.id, class: 'form-check-input',
                                   checked: role.code == 'USER'%>
                <%= f.label :role, role.name, class: 'form-check-label' %>
              </div>
            <% end %>
          </div>
        <% end %>

        <% if logged_in? && current_user.admin?%>
          <div class="form-group">
            <%= f.label 'Avatar:' %>
            <%= f.file_field :avatar %>
            <small class="text-danger"> <%= @user.errors[:avatar].first %> </small>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label 'Password:' %>
          <%= f.password_field :password, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @user.errors.messages[:password].first%>
          </small>
        </div>
        <div class="form-group">
          <%= f.label 'Password confirmation' %>
          <%= f.password_field :password_confirmation, class: 'form-control shadow-sm border-0 bg-light' %>
          <small class="text-danger">
            <%= @user.errors.messages[:password_confirmation].first%>
          </small>
        </div>

        <%= f.submit 'Register me', class: 'btn btn-primary btn-block btn-large' %>
      <% end %>

    </div>
  </div>
</div>