config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'articles#index'

  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
  get 'users', to: 'users#index'
  delete 'users/:id', to: 'users#destroy', as: 'user_delete'

  get 'profile/:id/edit', to: 'users#edit', as: 'edit_user'
  put 'profile/:id', to: 'users#update', as: 'user'

  get 'home', to: 'home#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles do
    resources :comments
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<div class="row mt-5">
  <div class="col-12 col-sm-10 col-lg-8 mx-auto">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> " role="alert">
          <%= message %>
        </div>
      <% end %>

  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand bg-white shadow">

  <%= link_to 'BLOG', home_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">

    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Article List', articles_path, class: 'nav-link' %>
      </li>
    </ul>
    <% if logged_in? %>
      <ul class="navbar-nav">
        <% if policy(Article).new? %>
          <li class="nav-item">
            <%= link_to 'New Article', new_article_path, class: 'nav-link' %>
          </li>
        <% end %>

        <% if policy(User).index? %>
          <li class="nav-item">
            <%= link_to 'User list', users_path, class: 'nav-link' %>
          </li>
        <% end %>

        <% if policy(User).new? %>
          <li class="nav-item">
            <%= link_to 'New user', register_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>


      <ul class="navbar-nav ml-auto ">
        <li class="nav-item dropdown">

          <a class="nav-link dropdown-toggle mr-5" href="#" data-toggle="dropdown">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar.variant(resize: "40x40"), class: 'rounded-circle' %>
            <% else %>
              <%= image_tag "no-user.png", alt: "NO USER", size: "40", class: 'rounded-circle' %>
            <% end %>
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu mr-5">
            <p class="dropdown-item"> <%= link_to 'Perfil', edit_user_path(current_user) %> </p>
            <div class="dropdown-divider"></div>
            <%= link_to 'Logout', logout_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>

    <% else %>
      <ul class="navbar-nav ml-auto ">
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Register', register_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capitulo06</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="fondo">
    <%= render 'layouts/navbar' %>

    <%= render 'layouts/flash_messages' %>

    <div class="mt-3">
      <%= yield %>
    </div>

  </body>
</html>